"""Applying account records to a running Mosquitto broker.

The records themselves live in `studio.models.config.mqtt_users` — that is the source
of truth, and it survives the broker directory being deleted. This file is the
other half: turning those records into the two files Mosquitto actually reads,
and telling a running broker to pick them up.

    passwd   username:hash, written by `mosquitto_passwd`
    acl      `user <name>` followed by its topic rules

Both are generated, both are disposable. Nothing here is asked what accounts
exist; it is told, and its job is only to make the broker agree.

The hash in `passwd` cannot be read back — that is Mosquitto's design, not an
accident — which is exactly why Studio keeps its own record of the password.
Before it did, every launch found a broker directory it could not read
credentials out of and minted a new `studio` password to compensate.
"""

from __future__ import annotations

import signal
import subprocess

from ....models.config.mqtt_users import MqttUser, users
from . import commands
from .finder import PASSWD_TOOL, find

COMMAND_TIMEOUT = 10

ACL_HEADER = """\
# Generated by Desk Buddy Studio from its account records. Edits here are
# overwritten; change accounts in Studio instead.
#
# Each account's topic list is its own. "#" reaches the whole broker; anything
# else is a specific tree, so unrelated accounts' traffic stays unreachable.
"""


def sync() -> str:
    """Make the broker's files match Studio's records. "" on success.

    Rewritten wholesale rather than diffed: the record file is small, the
    broker files are ours alone, and "make it match" has no partial-failure
    state to reason about the way a sequence of adds and removes would.
    """
    tool = find(PASSWD_TOOL)
    if not tool:
        return f"{PASSWD_TOOL} is not installed, so accounts cannot be applied."

    commands.ensure_account_files()
    entries = users().all()

    # Rewritten from empty so an account removed from the records is removed
    # from the broker too — `mosquitto_passwd -b` only ever adds or updates.
    passwd = commands.passwd_path()
    try:
        passwd.write_text("")
        passwd.chmod(0o600)
    except OSError as error:
        return str(error)

    for user in entries:
        if not user.password:
            # No recorded password means nothing to hash. Skipping keeps the
            # rest of the accounts working rather than failing the whole sync.
            continue
        problem = _run([tool, "-b", str(passwd), user.name, user.password])
        if problem is not None:
            return problem

    _write_acl(entries)
    reload_broker()
    return ""


def _write_acl(entries: list[MqttUser]) -> None:
    lines = [ACL_HEADER]
    for user in sorted(entries, key=lambda item: item.name):
        lines.append(f"user {user.name}")
        for topic in user.topics:
            lines.append(f"topic readwrite {topic}")
        lines.append("")

    path = commands.acl_path()
    path.write_text("\n".join(lines))
    path.chmod(0o600)


def reload_broker() -> bool:
    """Make a running broker re-read the account files, without dropping anyone.

    SIGHUP is verified to work: an account added to the files goes from refused
    to publishing with no restart and no dropped connections. Windows has no
    SIGHUP, so there the broker is restarted instead — connections drop, but
    correctness beats elegance and nothing is connected during setup anyway.
    """
    if not commands.is_ours():
        return False

    process = commands._process
    if process is None:
        return False

    if hasattr(signal, "SIGHUP"):
        process.send_signal(signal.SIGHUP)
        return True

    return bool(commands.restart())


def _run(argv: list[str]) -> str | None:
    """Run a mosquitto_passwd command. None on success, else the error text."""
    try:
        result = subprocess.run(
            argv, capture_output=True, text=True, timeout=COMMAND_TIMEOUT
        )
    except (OSError, subprocess.SubprocessError) as error:
        return str(error)

    if result.returncode == 0:
        return None

    # mosquitto_passwd's own message beats anything generic we would write.
    message = (result.stderr or result.stdout).strip()
    return message or f"{argv[0]} failed with code {result.returncode}."
