"""Start, stop and restart the broker Studio owns.

The finder answers "what is there?"; this answers "make it so". Split because
they fail differently: finding is read-only and safe to poll, while starting
spawns a process, writes files, and can fail in ways the user has to read.

Studio runs its **own** broker rather than touching the system one:

    ~/.local/share/DeskBuddy/Studio/broker/    (0700)
        mosquitto.conf    generated, ours, overwritten freely
        passwd            accounts, created in step 3
        acl               per-robot topic permissions, step 3

No root, no systemd, no service registration, nothing outside that directory.
Uninstalling Studio is deleting it. A broker the user set up themselves on 1883
is left alone — we neither reconfigure nor stop it.

Every command returns a `CommandResult` rather than raising: a broker that will
not start is a normal thing to report in the UI, not an exception to catch.
"""

from __future__ import annotations

import subprocess
import time
from dataclasses import dataclass
from pathlib import Path

from PySide6.QtCore import QCoreApplication, QStandardPaths

from ..user_config.settings import APP, ORG
from .broker_finder import DEFAULT_PORT, find, port_open

# How long to wait for the port to answer after a start, and for the process to
# go away after a stop. Mosquitto binds in well under a second locally; beyond
# this something is wrong and the user should hear about it.
START_TIMEOUT = 5.0
STOP_TIMEOUT = 5.0
POLL_INTERVAL = 0.05

# Config written fresh on every start: it is ours, and regenerating means a
# stale port or path can never linger from an older version of Studio.
CONFIG_TEMPLATE = """\
# Generated by Desk Buddy Studio. Edits are overwritten on the next start.
listener {port} {host}
allow_anonymous false
password_file {passwd}
acl_file {acl}
persistence true
persistence_location {data}/
"""

# Bound to localhost by default. A broker on 0.0.0.0 is reachable from every
# network the machine joins; reaching a real robot needs a deliberate choice,
# not a default. (Step 2's remaining [OPEN] is how that choice is offered.)
DEFAULT_HOST = "127.0.0.1"


@dataclass(frozen=True)
class CommandResult:
    """What happened, in a form the page can render directly."""

    ok: bool
    message: str
    detail: str = ""        # broker output when it failed; often the real answer

    def __bool__(self) -> bool:
        return self.ok


def broker_dir() -> Path:
    """Where our broker's files live. Created 0700 on first use.

    `mosquitto_passwd` warns about world-readable password files and future
    versions refuse to load them, so the permissions are set from the start.

    The org and app names are set here rather than assumed. QStandardPaths
    returns the bare ~/.local/share without them — and worse, once a
    QApplication exists Qt defaults applicationName() to the *script name*,
    which would scatter broker files into directories like `DeskBuddy/<stdin>`.
    Setting both unconditionally is what keeps the path stable no matter who
    imported this or how the process was launched.
    """
    QCoreApplication.setOrganizationName(ORG)
    QCoreApplication.setApplicationName(APP)

    root = QStandardPaths.writableLocation(QStandardPaths.AppLocalDataLocation)
    directory = Path(root) / "broker"
    directory.mkdir(parents=True, exist_ok=True)
    directory.chmod(0o700)
    return directory


def config_path() -> Path:
    return broker_dir() / "mosquitto.conf"


def passwd_path() -> Path:
    return broker_dir() / "passwd"


def acl_path() -> Path:
    return broker_dir() / "acl"


def write_config(port: int = DEFAULT_PORT, host: str = DEFAULT_HOST) -> Path:
    """Generate mosquitto.conf and the empty files it references.

    An empty password file is valid and correct here: with `allow_anonymous
    false` the broker starts and refuses everyone until step 3 adds accounts.
    That is the right default — an open broker would be worse.
    """
    directory = broker_dir()

    for path in (passwd_path(), acl_path()):
        if not path.exists():
            path.touch()
        path.chmod(0o600)

    config = config_path()
    config.write_text(
        CONFIG_TEMPLATE.format(
            port=port,
            host=host,
            passwd=passwd_path(),
            acl=acl_path(),
            data=directory,
        )
    )
    config.chmod(0o600)
    return config


# The running process, when we are the ones who started it. Studio may also be
# looking at a broker it did not start (a system one on 1883), which is exactly
# why stop() checks this before doing anything.
_process: subprocess.Popen | None = None

# The port we actually started on. Recorded rather than assumed: the finder
# would otherwise have to guess by scanning, and could report a different
# broker's port alongside `ours=True` — two facts about two different brokers.
_port: int = 0


def is_ours() -> bool:
    """True when Studio started the broker that is running."""
    return _process is not None and _process.poll() is None


def our_port() -> int:
    """The port our broker is on, or 0 when we are not running one."""
    return _port if is_ours() else 0


def start(port: int = DEFAULT_PORT, host: str = DEFAULT_HOST) -> CommandResult:
    """Start our broker and wait for it to actually accept connections."""
    global _process, _port

    if is_ours():
        return CommandResult(True, "Broker is already running.")

    binary = find("mosquitto")
    if not binary:
        return CommandResult(False, "Mosquitto is not installed.")

    if port_open(port, host):
        return CommandResult(
            False,
            f"Port {port} is already in use.",
            "Something is already listening there. Stop it, or point Studio "
            "at it instead of starting a second broker.",
        )

    config = write_config(port, host)

    try:
        process = subprocess.Popen(
            [binary, "-c", str(config)],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
    except OSError as error:
        return CommandResult(False, "Could not start the broker.", str(error))

    # Wait for the port, not just for the process — a broker that exits during
    # startup (bad config, port taken) is still a Popen object for a moment.
    deadline = time.monotonic() + START_TIMEOUT
    while time.monotonic() < deadline:
        if port_open(port, host):
            _process = process
            _port = port
            return CommandResult(True, f"Broker running on port {port}.")
        if process.poll() is not None:
            # It died. Mosquitto's own message is better than anything we would
            # write — "Error: Address already in use", with the config line.
            return CommandResult(
                False,
                "The broker stopped as it started.",
                _last_lines(process),
            )
        time.sleep(POLL_INTERVAL)

    process.terminate()
    return CommandResult(
        False,
        f"The broker did not open port {port} within {START_TIMEOUT:.0f}s.",
        _last_lines(process),
    )


def stop() -> CommandResult:
    """Stop the broker we started. Never touches one we did not."""
    global _process, _port

    if not is_ours():
        _process = None
        return CommandResult(
            False,
            "Studio did not start this broker.",
            "Only the broker Studio runs can be stopped from here — a system "
            "broker is left alone deliberately.",
        )

    process = _process
    process.terminate()
    try:
        process.wait(timeout=STOP_TIMEOUT)
    except subprocess.TimeoutExpired:
        process.kill()
        try:
            process.wait(timeout=STOP_TIMEOUT)
        except subprocess.TimeoutExpired:
            return CommandResult(False, "The broker did not stop.")
        _process = None
        return CommandResult(True, "Broker force-stopped.")

    _process = None
    _port = 0
    return CommandResult(True, "Broker stopped.")


def restart(port: int = DEFAULT_PORT, host: str = DEFAULT_HOST) -> CommandResult:
    """Stop then start. Reports the step that failed, not a generic error."""
    if is_ours():
        stopped = stop()
        if not stopped:
            return stopped
    return start(port, host)


def shutdown() -> None:
    """Stop our broker on app exit, so we never orphan a process.

    Deliberately silent: nothing can be shown to a window that is closing.
    """
    if is_ours():
        stop()


def _last_lines(process: subprocess.Popen, count: int = 3) -> str:
    """The tail of the broker's own output, for a failure the user must read."""
    if process.stdout is None:
        return ""
    try:
        output = process.stdout.read() or ""
    except (OSError, ValueError):
        return ""
    lines = [line.strip() for line in output.strip().splitlines() if line.strip()]
    return "\n".join(lines[-count:])
