name: Check for STL Files

on:
  pull_request:
    branches:
      - master

jobs:
  check-stl-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check for STL files
      run: |
        if git ls-files | grep -i '\.stl'; then
          echo "STL files found! Remove them before merging.";
          exit 1;
        else
          echo "No STL files found.";
        fi
